# Generated by Django 2.0.2 on 2021-12-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleF', models.CharField(max_length=60)),
                ('descriptionF', models.CharField(default='No description', max_length=200)),
                ('locationF', models.CharField(default='Dublin', max_length=60)),
                ('createdTimeF', models.DateTimeField(auto_now_add=True)),
                ('uploadTimeF', models.DateTimeField(auto_now_add=True)),
                ('weatherF', models.CharField(default='no info yet', max_length=20)),
                ('weatherdescriptionF', models.CharField(default='-', max_length=20)),
                ('weatericonF', models.CharField(default='-', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
