# Generated by Django 2.1.15 on 2021-11-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='genre',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='director',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='release_date',
        ),
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
