# Generated by Django 2.1.15 on 2021-11-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_feed_picturelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='pictureLink',
            field=models.CharField(max_length=200),
        ),
    ]
