# Generated by Django 2.1.15 on 2021-11-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_auto_20211107_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='descriptionF',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='pictureLink',
        ),
    ]
