# Generated by Django 2.1 on 2021-11-27 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_feed_descriptionf'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='uploadTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
