# Generated by Django 2.1 on 2021-11-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_auto_20211128_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='uploadTimeF',
            field=models.DateTimeField(),
        ),
    ]
