# Generated by Django 2.1 on 2021-11-28 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_remove_feed_uploadtimef'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='uploadTimeF',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
