# Generated by Django 2.1.15 on 2021-12-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0025_feed_createdtimef'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='weatherF',
            field=models.CharField(default=10, max_length=20),
            preserve_default=False,
        ),
    ]
