# Generated by Django 2.1.15 on 2021-12-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0027_auto_20211208_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='weatericonF',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='feed',
            name='weatherF',
            field=models.CharField(default='no info yet', max_length=20),
        ),
        migrations.AlterField(
            model_name='feed',
            name='weatherdescriptionF',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
