# Generated by Django 2.1.15 on 2021-11-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20211107_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='pictureLink',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
