# Generated by Django 2.1.15 on 2021-11-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20211107_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='description',
            new_name='descriptionF',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='title',
            new_name='titleF',
        ),
    ]
