# Generated by Django 2.1 on 2021-11-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_feed_uploadtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='uploadTime',
            new_name='uploadTimeF',
        ),
    ]
