# Generated by Django 2.1 on 2021-11-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_auto_20211128_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='uploadTimeF',
            field=models.CharField(default='timeGet', max_length=60),
        ),
    ]
