# Generated by Django 2.1.15 on 2021-12-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0023_auto_20211128_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='locationF',
            field=models.CharField(default='Dublin', max_length=60),
        ),
    ]
