# Generated by Django 2.1.15 on 2021-12-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0026_feed_weatherf'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='weatericonF',
            field=models.CharField(default=11, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='weatherdescriptionF',
            field=models.CharField(default=55, max_length=20),
            preserve_default=False,
        ),
    ]
