# Generated by Django 2.1.15 on 2021-11-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_auto_20211107_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='descriptionF',
            field=models.CharField(default='No description', max_length=200),
        ),
    ]
