# Generated by Django 2.1 on 2021-11-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_auto_20211128_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='uploadTimeF',
        ),
    ]
