# Generated by Django 2.1 on 2021-11-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0014_feed_uploadtimef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='uploadTimeF',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
