# Generated by Django 2.1 on 2021-11-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0022_auto_20211128_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='uploadTimeF',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
