# Generated by Django 2.0.2 on 2021-12-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0029_feed_picturef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='pictureF',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
