# Generated by Django 2.0.2 on 2021-12-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0030_auto_20211215_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='pictureF',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
